cat > .github/workflows/backend-ci.yml << 'EOF'
name: Backend CI

on:
  push:
    paths:
      - '**/pom.xml'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [auth-service, gateway, trade-service, market-data-service, portfolio-service, notification-service]

    defaults:
      run:
        working-directory: ${{ matrix.service }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install
EOF
